### ISSUE TITLE
How to connect with store

### ISSUE THREAD

**Issue by Sanjay-100** [Shopify/shopify-marketplaces-buyer-app#2]
How to connect with store

**Comment by Karen-boop** [comment]
Hi Sanjay, [this tutorial](https://shopify.dev/marketplaces/getting-started/connect-marketplace-homepage) will walk you through connecting to a store. Is there any particular step that is giving difficulty?

**Comment by Sanjay-100** [comment]
@Karen-boop   
I am getting Those errors.
steps i did

`shopify app serve
`

this connecd create .env on project root but give this error
![image](https://user-images.githubusercontent.com/98302784/161900469-7ba8b607-fafe-4476-aeb2-3682721404cf.png)

**Comment by Karen-boop** [comment]
Thanks for clarifying @Sanjay-100. 
This repo ([shopify-marketplaces-buyer-app](https://github.com/Shopify/shopify-marketplaces-buyer-app)) does not use the Shopify CLI so you do not need `shopify app serve` to run it. You can simply follow the instructions in this [repo's readme](https://github.com/Shopify/shopify-marketplaces-buyer-app#1-getting-started) to get the buyer facing marketplace up and running. 

Once you have the buyer facing up and running you will need to install your [admin app](https://github.com/Shopify/shopify-marketplaces-admin-app) on a development store and follow the Marketplace Kit tutorials too connect the two.
